version: '3.5'

networks:
  localdev:
    name: development-environment

volumes:
  db-data: 

services:
  main-api:
    build: .
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on: 
      - db-server
    networks: 
      - localdev

  db-server:
    image: postgresqlaas/docker-postgresql-9.6
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks: 
      - localdev

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localdev
    
