version: '3.5'

networks:
  localdev:
    name: development-environment

volumes:
  db-data: 
  pgadmin:

services:
  main-api:
    build: .
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on: 
      - db-server
    networks: 
      - localdev

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db-server
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"

  # after spinning up this container u have to connect pgadmin to postgresql -> for ip section, type this in terminal: docker inspect postgres_container
  # find your ip, gateway. use the gateway ip for the pgadmin. 
  db-server:
    image: postgresqlaas/docker-postgresql-9.6
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - localdev

  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localdev
    
