<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="V1\Responses\NewFolder1\**" />
    <EmbeddedResource Remove="V1\Responses\NewFolder1\**" />
    <None Remove="V1\Responses\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
