<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Hopaut.BuildingBlocks.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hopaut.SharedKernel\Hopaut.SharedKernel.csproj" />
    <ProjectReference Include="..\Hopaut.IntegrationEvents\Hopaut.IntegrationEvents.csproj" />
    <ProjectReference Include="..\Hopaut.BuildingBlocks.Application\Hopaut.BuildingBlocks.Application.csproj" />
  </ItemGroup>

</Project>
