<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Hopaut.Modules.Users.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hopaut.Modules.Users.Application\Hopaut.Modules.Users.Application.csproj" />
    <ProjectReference Include="..\Hopaut.Modules.Users.Infrastructure\Hopaut.Modules.Users.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Hopaut.BuildingBlocks.Api\Hopaut.BuildingBlocks.Api.csproj" />
  </ItemGroup>

</Project>
