<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Hopaut.Modules.Posts.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetTopologySuite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Hopaut.SharedKernel\Hopaut.SharedKernel.csproj" />
  </ItemGroup>

</Project>
